version: '3.9'

services:
  reyland-site:
    build: .
    image: la-config-reyland-site:latest
    ports: [ "7070:7070" ]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    hostname: la-config-reyland-site
    container_name: la-config-reyland-site
    network_mode: bridge
    restart: always
